### ISSUE TITLE
error installing

### ISSUE THREAD

**Issue by mph070770** [haade-administrator/korvo-esphome#1]
Hi!
I'm trying to install your code and get the following error:

INFO ESPHome 2023.9.3
INFO Reading configuration /config/esphome/esphome-web-e6af84.yaml...
ERROR Unexpected exception while reading configuration:
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 33, in <module>
    sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
  File "/esphome/esphome/__main__.py", line 1036, in main
    return run_esphome(sys.argv)
  File "/esphome/esphome/__main__.py", line 1014, in run_esphome
    config = read_config(dict(args.substitution) if args.substitution else {})
  File "/esphome/esphome/config.py", line 986, in read_config
    res = load_config(command_line_substitutions)
  File "/esphome/esphome/config.py", line 840, in load_config
    return _load_config(command_line_substitutions)
  File "/esphome/esphome/config.py", line 828, in _load_config
    result = validate_config(config, command_line_substitutions)
  File "/esphome/esphome/config.py", line 690, in validate_config
    substitutions.do_substitution_pass(config, command_line_substitutions)
  File "/esphome/esphome/components/substitutions/__init__.py", line 143, in do_substitution_pass
    config.move_to_end(CONF_SUBSTITUTIONS, False)
AttributeError: 'dict' object has no attribute 'move_to_end'

Could you help please?

**Comment by haade-administrator** [comment]
hello update esphome min version is 2023.11.0

**Comment by mph070770** [comment]
Thanks @haade-administrator that worked.  Sorry - should have seen the outdated status of ESPHome.  

I've got further with the install but now I get this error about pin 0.

INFO ESPHome 2023.12.6
INFO Reading configuration /config/esphome/esphome-web-e6af84.yaml...
WARNING 'esp32korvo_mic': Using the '_' (underscore) character in the hostname is discouraged as it can cause problems with some DHCP and local name services. For more information, see https://esphome.io/guides/faq.html#why-shouldn-t-i-use-underscores-in-my-device-name
INFO Detected timezone 'Europe/London'
WARNING GPIO12 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING GPIO0 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
WARNING GPIO0 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
Failed config

i2s_audio: [source /data/packages/6aa459db/esp32korvo_esphome.yaml:87]
  
  Pin 0 is used in multiple places.
  - id: codec
    i2s_lrclk_pin: 22
    i2s_bclk_pin: 25
    i2s_mclk_pin: 0
  
  Pin 0 is used in multiple places.
  - id: mic_adc
    i2s_lrclk_pin: 26
    i2s_bclk_pin: 27
    i2s_mclk_pin: 0

**Comment by mph070770** [comment]
Needs to change to this:

```
i2s_audio:
  - id: codec
    i2s_lrclk_pin: GPIO22
    i2s_bclk_pin: GPIO25
    i2s_mclk_pin:
      number: GPIO0
      allow_other_uses: true
  - id: mic_adc
    i2s_lrclk_pin: GPIO26
    i2s_bclk_pin: GPIO27
    i2s_mclk_pin: 
      number: GPIO0
      allow_other_uses: true
```
